variable "resource_group" {}
variable "lwk_name" {}
variable "lwk_resource_group_name" {}
variable "namespace_name" {}
variable "event_hub_sku_tier" {}
variable "suffixnames_eh" {}
variable "name" {}
variable "location" {}
variable "eventhub_auth_rules" {}
variable "namespace_auth_rules" {}
variable "analytics_diagnostic_monitor" {}
variable "event_hub_ips_filter" {}
variable "event_hub_snet_ids" {}
variable "cost_center" {}
variable "product" {}
variable "channel" {}
variable "description" {}
variable "tracking_code" {}
variable "cia" {}
